# ksqlDB. Required by Control Center for stream processing UI.
# Apply after Kafka is ready.
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
spec:
  replicas: 1
  image:
    application: confluentinc/cp-ksqldb-server:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
    pullPolicy: IfNotPresent
  dataVolumeCapacity: 10Gi
